### ISSUE TITLE
Added support for require('load-grunt-tasks')(grunt);

### ISSUE THREAD

**Issue by niemyjski** [nikestep/grunt-html-angular-validate#12]

**Comment by boyomarinov** [comment]
I think this issue can be closed - there is no need for additional support in the library itself. `htmlangular.js` file that exports plugin configuration should be added in tasks directory specified by `load-grunt-tasks` and it works properly.

**Comment by niemyjski** [comment]
Hey,

I just thought it would clean up my scripts. Sorry for not responding sooner.

@boyomarinov can you please let me know where I could [set this at](https://github.com/exceptionless/Exceptionless.ui)? I'm a nub in this regards.
