### ISSUE TITLE
Validating template of angular directive with <tr attribute> root

### ISSUE THREAD

**Issue by ptanov** [nikestep/grunt-html-angular-validate#17]
Hello Nik Estep,
I have found an issue related to this issue:
https://github.com/nikestep/grunt-html-angular-validate/issues/4

When one has a root element containing an attribute, e.g.:
`<tr data-ng-click="something"></tr>`
then the check:
                        `var tag = '<' + key + '>';`
                        `if (content.indexOf(tag) === 0) {`
 does not pass.

I can think of a couple of options:
1) fast fix:
                        `var tag1 = '<' + key + '>';`
                        `var tag2 = '<' + key + ' ';`
                        `if (content.indexOf(tag1) === 0 || content.indexOf(tag2) === 0) {`
2) using regex:
                        `var tag = '^<' + key + '[^>]*>';`
                        `if (content.match(tag)) {`

Thank you very much in advance,
Plamen

**Comment by nikestep** [comment]
So sorry for the long delay in implementing this fix. Thank you for the suggestion!

**Comment by ptanov** [comment]
Thank you very much!
