### ISSUE TITLE
Validation error when input element's "type" field is an Angular expression

### ISSUE THREAD

**Issue by ionthegeek** [nikestep/grunt-html-angular-validate#18]
I'm having an issue similar to #6, except in my case it's complaining about an Angular expression in the type field of an input element.

For example, I have HTML similar to the following in the template file for a directive:
`<input id="{{ field.id }}" name="{{ field.id }}" type="{{ field.type }}" />`

This produces the following error:
`[L3:C165] Bad value {{field.type}} for attribute type on element input`

Is there a way to tell the plug-in to ignore this error for Angular expressions?

**Comment by chriskuehl** [comment]
Do you know if such code is supported cross-browser? There is a lot of information on the internet suggesting that changing the type on-the-fly is poorly supported, e.g.: http://stackoverflow.com/q/15148456

I also found a few comments suggesting that newer Angular versions support this, but can't find anything in release notes. I'm wondering because if it's not actually supported, then it probably makes sense to keep the error message as-is.

**Comment by ionthegeek** [comment]
In my case the type doesn't actually change, it's just part of a template that supports multiple types. For example the following directive:
`<form-row field-id="username" field-label="Username" type="text"></form-row>`

...becomes something like:
`<div class="form-row">`
`  <label for="username">Username</label>`
`  <input id="username" name="username" type="text" />`
`</div>`

The fields are statically rendered into the template before the template is inserted into the page.

**Comment by chriskuehl** [comment]
Ah, that makes sense.

Unfortunately I'm not really sure how this would reasonably be fixed without just suppressing the error messages. The validation service will, of course, complain about it, so unless the code was changed to either swap expressions for some default value like `text` before sending them to the validator (which seems like a bad idea), I don't see a good way to fix this.

The best solutions I can see are to either silently drop these `<input>` elements before validation (which means other attributes wouldn't be validated), or to suppress the error messages.

Given that this seems like a pretty rare problem, I wonder if it would make more sense for you to just suppress them locally (e.g. add them to `options.relaxerror` in your Gruntfile)? I'm guessing for most people, this type of message would actually indicate an error, so suppressing them for everyone could be dangerous. What are your thoughts?

**Comment by ionthegeek** [comment]
I agree, this isn't an easy problem to solve. My only concern with relaxerror is that it doesn't seem to be granular. I'm concerned with disabling the error message globally for the reasons you've mentioned since it's possible I'll make a mistake elsewhere in the project.

Maybe it would be possible to implement something similar to jshint's ability to disable or enable specific warnings mid-file? For example, you can disable a jshint warning in a specific section of code like this:

`<code to be checked>`
`/* jshint -W034 */`
`<code not checked>`
`/* jshint +W034 */`
`<more code to be checked>`

I realize this might not be practical since the validation output is coming back from an outside service. In the meantime, I'll see if it's possible to relax the error just for that specific file with some Gruntfile gymnastics.

Thanks!
