### ISSUE TITLE
Consider using ng-directive-parser to populate custom tags/attributes

### ISSUE THREAD

**Issue by schmod** [nikestep/grunt-html-angular-validate#21]
Consider utilizing [ng-directive-parser](https://github.com/jantimon/ng-directive-parser) to crawl through a project's script files so that the array of allowable custom tags/attributes can be automagically populated.

**Comment by nikestep** [comment]
Please post on [nikestep/html-angular-validate](https://github.com/nikestep/html-angular-validate/issues)
