### ISSUE TITLE
Can get relaxerror to work

### ISSUE THREAD

**Issue by justechn** [nikestep/grunt-html-angular-validate#26]
I have this option
```
relaxerror: [
    'The “name” attribute is obsolete. Consider putting an “id” attribute on the nearest container instead.'
],
```

but I am still seeing that error from the validator

**Comment by nikestep** [comment]
What version are you using?

**Comment by chriskuehl** [comment]
Just a thought, but is your code definitely using the "fancy" quotes like in the error message? And is your Gruntfile being properly saved with UTF-8?

It's working for me on the latest version (0.5.0) of the library to ignore that error message, but only if I use the fancy quotes and my Gruntfile is utf-8.

**Comment by nikestep** [comment]
Yeah, the fancy quotes seem to  be a change that results from changes in either the w3c library or the validator itself.

**Comment by justechn** [comment]
I am using 0.5.0, and I know that I am using the "fancy" quotes (I copied the text directly from the terminal output), but I don't know if I am using utf-8. I will check when I get back to the office on Monday.

**Comment by justechn** [comment]
the file was not utf-8. once I switched it started working.

**Comment by jdoose** [comment]
Maybe this is worth mentioning in the documentation for relaxerror.
I also copied it from the console, thus the text got changed to regular quotes. Took me quite some time and debugging to find out.
