### ISSUE TITLE
Create gulp version

### ISSUE THREAD

**Issue by ptarjan** [nikestep/grunt-html-angular-validate#28]
Is it difficult to abstract this plugin to a generic linter so we could have other build system integrations (and a CLI)?

I personally use gulp for my team's project and would love to lint our templates.

**Comment by nikestep** [comment]
It may be possible to take the core functionality and abstract it into its own node module and then create a gulp plugin wrapping it. This project would be a grunt plugin wrapper.

I don't personally use gulp, but I'll take a look.

**Comment by nikestep** [comment]
I refactored this plugin to move the core validation functionality to its own module. Next up would be to create a gulp plugin, though that may take longer as I've not used gulp :)

**Comment by nikestep** [comment]
Actually, after some reading it looks like this shouldn't be a plugin, but rather just a task that uses the new module I built.

I created a recipe: https://github.com/nikestep/html-angular-validate/blob/master/gulpfile.js

**Comment by ptarjan** [comment]
Nice, thanks. If you expose your `lib/validate.js` in your `package.json` then I can just `npm install` it and use it from my gulp file.

**Comment by nikestep** [comment]
Sorry, but I'm not sure I understand. I pulled it into a test project and it worked just fine. `lib/validate.js` is exposed through `main` already. All you should need is `var validate = require('html-angular-validate');`

**Comment by ptarjan** [comment]
My fault, I didn't see https://github.com/nikestep/html-angular-validate/blob/master/package.json#L11 . Thanks!

**Comment by ewu02** [comment]
Why don't you think this should be a plugin? It would be more convenient to incorporate into existing gulp projects. Currently writing a prototype, which is coming along well. I'll post it up when it's done. Would be great to get your thoughts.

**Comment by ewu02** [comment]
here's the initial version
https://github.com/ewu02/gulp-html-angular-validate

**Comment by nikestep** [comment]
I was reading about how to write gulp plugins and a few places discouraged just wrapping npm packages as gulp plugins, so I opted not to. I think what you're wrote looks good, but I would have tests on it before you release it to the world.

**Comment by ewu02** [comment]
That's great. And yea, going to have tests for it shortly.
