### ISSUE TITLE
Support for different report file formats (checkstyle)?

### ISSUE THREAD

**Issue by dpalic** [nikestep/grunt-html-angular-validate#30]
Since I am not sure, if it should be an option of the grunt-runner or from html-angular-validate directly, here a crossposting.

https://github.com/nikestep/html-angular-validate/issues/5

It would be great to let us know if there is any plan to support checkstyle.xml-format, else we will have to do some workarounds for us.

best wishes

**Comment by nikestep** [comment]
Fixed in v0.5.4
