### ISSUE TITLE
Element “title” must not be empty.

### ISSUE THREAD

**Issue by pbfrederiksen** [nikestep/grunt-html-angular-validate#31]
I get this validation error in all my title elements: *Element “title” must not be empty.*
I use ng-bind so title will be filled by angularJS.

Is there a way to let the validator accept this html:
```
<html lang="en" ng-app="IncidentLogViewerMaster">
<head>
    <title ng-bind="appName"></title>
...
```

appName is defined in $rootScope.

Peter

**Comment by nikestep** [comment]
Please post on nikestep/html-angular-validate
