### ISSUE TITLE
Getting Fatal error: Cannot read property 'messages' of null

### ISSUE THREAD

**Issue by ftdube** [nikestep/grunt-html-angular-validate#37]
Hi,

Overnight, it seems like one of the dependencies from grunt-html-angular-validate, w3cjs, got an update from version 0.3.0 to 0.3.1 and a bunch of its own dependencies have changed.  From that point on, whenever I try to run htmlangular from grunt, I get the following message : 
```
Running "htmlangular:main" (htmlangular) task
Fatal error: Cannot read property 'messages' of null

Process finished with exit code 3
```

Does that ring a bell to anyone?  Is there an easy way to fix this?

**Comment by rreitmann** [comment]
We are experiencing the same issue. Any suggestions for fixing this?

**Comment by rreitmann** [comment]
Fixed with update of w3cjs (see thomasdavis/w3cjs#33)
